# file: /usr/lib/python3/dist-packages/urllib3/exceptions.py
# hypothesis_version: 6.139.1

['localhost']