# file: /usr/lib/python3/dist-packages/attr/exceptions.py
# hypothesis_version: 6.139.1

["can't set attribute"]